all:
	$(MAKE) -C src/Render
	$(MAKE) -C src/ScenegraphLocationDelegate
	$(MAKE) -C src/RendererInfo
	@echo "Build done."

clean:
	$(MAKE) -C src/Render clean
	$(MAKE) -C src/ScenegraphLocationDelegate clean
	$(MAKE) -C src/RendererInfo clean

